name: Coverage

on: ["push"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Cache Nix store
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build coverage using pytest-cov
      run: |
        nix develop --command bash -c "uv run pytest -n auto -m 'not slow' --cov --cov-fail-under=74 --cov-report=xml --cov-report=term-missing"

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
